### ISSUE TITLE
Reverse Java-11 specific workaround in gradle.properties

### ISSUE THREAD

**Issue by damithc** [nus-oss/AB3-J17#18]
See if we can reverse this now ...

https://github.com/se-edu/addressbook-level3/commit/09837d98cc0443a75e7291e6aceb76764e18ca04

**Comment by aureliony** [comment]
I have tested reverting the TLS workaround, and encountered no issues with GH Actions. Both Java CI and Codecov are working as expected.

https://github.com/aureliony/AB3-J17/commit/549e670609793a8ef62b7a7cb6f0cfc11309c4ff

**Comment by damithc** [comment]
Thanks for checking @aureliony 
Go ahead and send a PR for this.
