### ISSUE TITLE
Update CI script to match newer versions of the tools used

### ISSUE THREAD

**Issue by damithc** [nus-oss/AB3-J17#26]
Investigate the need for the following changes to `.github/workflows/gradle.yml` in https://github.com/nus-oss/AB3-J17/pull/4/files (by @brein62), and if justified, send PRs to update each.

![image](https://github.com/user-attachments/assets/8e0d625d-c5a8-45ba-a291-c919aeb6b20c)

**Comment by aureliony** [comment]
There is no real need to bump the workflow versions as the current ones are still working fine, but it would be good to update to the latest versions to minimize the possibility of things breaking in the future.

**Comment by brein62** [comment]
As of now the old versions of the workflow actions are currently working perfectly fine with GitHub Actions, but do generate several warnings regarding the use of old Node versions (within the GitHub actions) which I felt that might lead to possibly dropped support or unintended outcomes when GitHub CI actions are performed in the future.

With the changes reflected, the actions still work properly and there are no longer any warnings.

Thus, these changes are **not strictly needed for now**, but **good to have** for future-proofing CI workflows (at least for the next few batches of CS2103/T students).

![IMG_6041](https://github.com/user-attachments/assets/92a68aa8-6fef-44a7-a98c-d425c08a1109)

![IMG_6042](https://github.com/user-attachments/assets/96783f6e-1809-45e0-bea1-e505c9af2afc)

**Comment by damithc** [comment]
Thanks for the inputs so far @brein62 @aureliony 
I'm leaning towards updating. So, feel free to send PRs for the required updates.
