### ISSUE TITLE
Update URL of SE-EDU / Contributing section in README file

### ISSUE THREAD

**Issue by jyue487** [nus-oss/AB3-J17#34]
Context:
<img width="1000" alt="Screenshot 2024-07-27 at 11 56 54 AM" src="https://github.com/user-attachments/assets/e89eb0e6-91ff-415d-96b3-a688b3381488">

A minor issue here. It seems that this url format is quite weird to me, although it has failed to direct me to the correct site from IntelliJ, clicking the link from the README file works perfectly. Perhaps it could be changed to a more familiar url like "https://se-education.org/#contributing" instead of "https://se-education.org#https://se-education.org/#contributing"

**Comment by damithc** [comment]
Good catch @jyue487 
Feel free to send a PR
